----------------------------------------------------------------
-- You can put defaults on the recipe itself:
--   equip = { primary="Base.BlowTorch", wearTag="WeldingMask" }
--   anim  = "Welding"
--   sound = "BlowTorch"          -- loops during repair (if set)
--   successSound = "SomeEvent"   -- plays after a successful repair (optional)
--   time  = function(player, brokenItem) return 160 end  -- or a number
--
-- globalItem supports:
--   { item="<FullType>", uses=3, consume=true }
--   { tag ="<TagName>",  uses=3, consume=true }
-- If consume=false, the item is required but NOT consumed.
----------------------------------------------------------------

return {
  recipes = {
    {
      name = "Fix Gas Tank Welding",
      require = {
        "Base.NormalGasTank1","Base.BigGasTank1","Base.NormalGasTank2","Base.BigGasTank2",
        "Base.NormalGasTank3","Base.BigGasTank3","Base.NormalGasTank8","Base.BigGasTank8",
        "Base.U1550LGasTank2","Base.MH_MkIIgastank1","Base.MH_MkIIgastank2","Base.MH_MkIIgastank3",
        "Base.M35FuelTank2","Base.NivaGasTank1","Base.97BushGasTank2","Base.ShermanGasTank2","Base.87fordF700GasTank2",
      },
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 0.8,
      -- Recipe-level defaults (fixers can override)
      equip = { primary = "Base.BlowTorch", wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallSheetMetal",   uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperSheet",       uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallCopperSheet",  uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.GoldSheet",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SilverSheet",       uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallArmorPlate",   uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.AluminumScrap",     uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.BrassScrap",        uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.IronScrap",         uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.ScrapMetal",        uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SteelScrap",        uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.UnusableMetal",     uses=8, skills={ MetalWelding=3, Mechanics=3 } },
      },
    },

    {
      name = "Fix Gas Tank",
      require = {
        "Base.NormalGasTank1","Base.BigGasTank1","Base.NormalGasTank2","Base.BigGasTank2",
        "Base.NormalGasTank3","Base.BigGasTank3","Base.NormalGasTank8","Base.BigGasTank8",
        "Base.U1550LGasTank2","Base.MH_MkIIgastank1","Base.MH_MkIIgastank2","Base.MH_MkIIgastank3",
        "Base.M35FuelTank2","Base.NivaGasTank1","Base.97BushGasTank2","Base.ShermanGasTank2","Base.87fordF700GasTank2",
      },
      conditionModifier = 0.3,
      anim = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.Epoxy",          uses=2, skills={ Mechanics=3 } },
        { item="Base.Glue",           uses=4, skills={ Mechanics=3 } },
        { item="Base.DuctTape",       uses=4, skills={ Mechanics=3 }, successSound="FixWithTape" },
        { item="Base.FiberglassTape", uses=2, skills={ Mechanics=3 }, successSound="FixWithTape" },
        { item="Base.Zipties",        uses=4, skills={ Mechanics=3 } },
        { item="Base.Gum",            uses=4, skills={ Mechanics=3 } },
      },
    },

    {
      name = "Fix Gas Tank Small Welding",
      require = {
        "Base.SmallGasTank1","Base.SmallGasTank2","Base.SmallGasTank3","Base.SmallGasTank8",
        "Base.SmallCycleGasTank","Base.CycleGasTank","Base.ATAMotoBMWGasTank","Base.ATAMotoHarleyGasTank",
        "Base.KZ1KgasTank","Base.SS100gasTank3","Base.ZNL50gasTank",
      },
      globalItem = { item = "Base.BlowTorch", uses = 2, consume = true },
      conditionModifier = 0.6,
      equip = { primary = "Base.BlowTorch", wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",        uses=1, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.SmallSheetMetal",   uses=2, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.CopperSheet",       uses=1, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.SmallCopperSheet",  uses=2, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.GoldSheet",         uses=1, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.SilverSheet",       uses=1, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.SmallArmorPlate",   uses=2, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.AluminumScrap",     uses=8, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.BrassScrap",        uses=8, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.CopperScrap",       uses=8, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.IronScrap",         uses=8, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.ScrapMetal",        uses=8, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.SteelScrap",        uses=8, skills={ MetalWelding=3, Mechanics=2 } },
        { item="Base.UnusableMetal",     uses=8, skills={ MetalWelding=3, Mechanics=2 } },
      },
    },

    {
      name = "Fix Gas Tank Small",
      require = {
        "Base.SmallGasTank1","Base.SmallGasTank2","Base.SmallGasTank3","Base.SmallGasTank8",
        "Base.SmallCycleGasTank","Base.CycleGasTank","Base.ATAMotoBMWGasTank","Base.ATAMotoHarleyGasTank",
        "Base.KZ1KgasTank","Base.SS100gasTank3","Base.ZNL50gasTank",
      },
      conditionModifier = 0.3,
      anim = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.Epoxy",          uses=2, skills={ Mechanics=2 } },
        { item="Base.Glue",           uses=2, skills={ Mechanics=2 } },
        { item="Base.DuctTape",       uses=2, skills={ Mechanics=2 }, successSound="FixWithTape" },
        { item="Base.FiberglassTape", uses=2, skills={ Mechanics=2 }, successSound="FixWithTape" },
        { item="Base.Gum",            uses=2, skills={ Mechanics=2 } },
        { item="Base.Zipties",        uses=2, skills={ Mechanics=2 } },
      },
    },

    {
      name = "Fix Trailer Welding",
      require = {
        "Base.TrailerTrunk1","Base.TrailerTrunk2","Base.TrailerTrunk3",
        "Base.FRTrailerTrunk1","Base.FRTrailerTrunk2","Base.FRTrailerTrunk3",
        "Base.FRXLCargoTrunk1","Base.FRXLCargoTrunk2","Base.FRXLCargoTrunk3","Base.FRXLCargoTrunk8",
        "Base.FRCargoTrunk1","Base.FRCargoTrunk2","Base.FRCargoTrunk3","Base.FRCargoTrunk8",
        "Base.IsoContainerTrunkDoor2","Base.IsoContainerDoubleTrunkDoor2","Base.IsoContainerTankerTrunkDoor2",
        "Base.ISOHalfStorage2","Base.TrailerFirstTrunk","Base.TrailerSecondTrunk",
      },
      globalItem = { item = "Base.BlowTorch", uses = 5, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallSheetMetal",  uses=4, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperSheet",      uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallCopperSheet", uses=4, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.GoldSheet",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SilverSheet",      uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallArmorPlate",  uses=3, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.MetalPipe",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.MetalBar",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.LeadPipe",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.AluminumScrap",    uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.BrassScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperScrap",      uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.IronScrap",        uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.ScrapMetal",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SteelScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.UnusableMetal",    uses=8, skills={ MetalWelding=3, Mechanics=3 } },
      },
    },

    {
      name = "Fix Trailer",
      require = {
        "Base.TrailerTrunk1","Base.TrailerTrunk2","Base.TrailerTrunk3",
        "Base.FRTrailerTrunk1","Base.FRTrailerTrunk2","Base.FRTrailerTrunk3",
        "Base.FRXLCargoTrunk1","Base.FRXLCargoTrunk2","Base.FRXLCargoTrunk3","Base.FRXLCargoTrunk8",
        "Base.FRCargoTrunk1","Base.FRCargoTrunk2","Base.FRCargoTrunk3","Base.FRCargoTrunk8",
        "Base.IsoContainerTrunkDoor2","Base.IsoContainerDoubleTrunkDoor2","Base.IsoContainerTankerTrunkDoor2",
        "Base.ISOHalfStorage2","Base.TrailerFirstTrunk","Base.TrailerSecondTrunk",
      },
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.7,
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=2, skills={ Mechanics=3 } },
        { item="Base.SmallSheetMetal",  uses=4, skills={ Mechanics=3 } },
        { item="Base.CopperSheet",      uses=2, skills={ Mechanics=3 } },
        { item="Base.SmallCopperSheet", uses=4, skills={ Mechanics=3 } },
        { item="Base.GoldSheet",        uses=1, skills={ Mechanics=3 } },
        { item="Base.SilverSheet",      uses=1, skills={ Mechanics=3 } },
        { item="Base.SmallArmorPlate",  uses=3, skills={ Mechanics=3 } },
        { item="Base.MetalPipe",        uses=1, skills={ Mechanics=3 } },
        { item="Base.MetalBar",         uses=1, skills={ Mechanics=3 } },
        { item="Base.LeadPipe",         uses=1, skills={ Mechanics=3 } },
        { item="Base.Plank",            uses=4, skills={ Woodwork=3, Mechanics=3 } },
        { item="Base.AluminumScrap",    uses=8, skills={ Mechanics=3 } },
        { item="Base.BrassScrap",       uses=8, skills={ Mechanics=3 } },
        { item="Base.CopperScrap",      uses=8, skills={ Mechanics=3 } },
        { item="Base.IronScrap",        uses=8, skills={ Mechanics=3 } },
        { item="Base.ScrapMetal",       uses=8, skills={ Mechanics=3 } },
        { item="Base.SteelScrap",       uses=8, skills={ Mechanics=3 } },
        { item="Base.UnusableMetal",    uses=8, skills={ Mechanics=3 } },
      },
    },

    {
      name = "Fix Trailer 1",
      require = {
        "Base.TrailerTrunk1","Base.TrailerTrunk2","Base.TrailerTrunk3",
        "Base.FRTrailerTrunk1","Base.FRTrailerTrunk2","Base.FRTrailerTrunk3",
        "Base.FRXLCargoTrunk1","Base.FRXLCargoTrunk2","Base.FRXLCargoTrunk3","Base.FRXLCargoTrunk8",
        "Base.FRCargoTrunk1","Base.FRCargoTrunk2","Base.FRCargoTrunk3","Base.FRCargoTrunk8",
        "Base.IsoContainerTrunkDoor2","Base.IsoContainerDoubleTrunkDoor2","Base.IsoContainerTankerTrunkDoor2",
        "Base.ISOHalfStorage2","Base.TrailerFirstTrunk","Base.TrailerSecondTrunk",
        },
      conditionModifier = 0.3,
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.Epoxy",          uses=2, skills={ Mechanics=2 } },
        { item="Base.Glue",           uses=4, skills={ Mechanics=2 } },
        { item="Base.DuctTape",       uses=4, skills={ Mechanics=2 }, successSound = "FixWithTape" },
        { item="Base.FiberglassTape", uses=2, skills={ Mechanics=2 }, successSound = "FixWithTape" },
        { item="Base.Zipties",        uses=4, skills={ Mechanics=2 } },
      },
    },

    {
      name = "Fix Trailer Lids Welding",
      require = {
        "Base.M101A3Cover1_Item",
        "Base.FRSideContainer1","Base.FRSideContainer2","Base.FRSideContainer3","Base.FRSideContainer8",
        "Base.FRSideContainer_RS1","Base.FRSideContainer_RS2","Base.FRSideContainer_RS3",
      },
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 1.0,
      equip = { primary = "Base.BlowTorch", wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallSheetMetal",  uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperSheet",      uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallCopperSheet", uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.GoldSheet",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SilverSheet",      uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallArmorPlate",  uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.MetalPipe",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.MetalBar",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.LeadPipe",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.AluminumScrap",    uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.BrassScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperScrap",      uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.IronScrap",        uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.ScrapMetal",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SteelScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.UnusableMetal",    uses=8, skills={ MetalWelding=3, Mechanics=3 } },
      },
    },

    {
      name = "Fix Trailer Lids",
      require = {
        "Base.M101A3Cover1_Item",
        "Base.FRSideContainer1","Base.FRSideContainer2","Base.FRSideContainer3","Base.FRSideContainer8",
        "Base.FRSideContainer_RS1","Base.FRSideContainer_RS2","Base.FRSideContainer_RS3",
      },
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.7,
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=1, skills={ Mechanics=3 } },
        { item="Base.SmallSheetMetal",  uses=2, skills={ Mechanics=3 } },
        { item="Base.CopperSheet",      uses=1, skills={ Mechanics=3 } },
        { item="Base.SmallCopperSheet", uses=2, skills={ Mechanics=3 } },
        { item="Base.GoldSheet",        uses=1, skills={ Mechanics=3 } },
        { item="Base.SilverSheet",      uses=1, skills={ Mechanics=3 } },
        { item="Base.SmallArmorPlate",  uses=2, skills={ Mechanics=3 } },
        { item="Base.MetalPipe",        uses=1, skills={ Mechanics=3 } },
        { item="Base.MetalBar",         uses=1, skills={ Mechanics=3 } },
        { item="Base.LeadPipe",         uses=1, skills={ Mechanics=3 } },
        { item="Base.Plank",            uses=2, skills={ Woodwork=3, Mechanics=3 } },
        { item="Base.AluminumScrap",    uses=8, skills={ Mechanics=3 } },
        { item="Base.BrassScrap",       uses=8, skills={ Mechanics=3 } },
        { item="Base.CopperScrap",      uses=8, skills={ Mechanics=3 } },
        { item="Base.IronScrap",        uses=8, skills={ Mechanics=3 } },
        { item="Base.ScrapMetal",       uses=8, skills={ Mechanics=3 } },
        { item="Base.SteelScrap",       uses=8, skills={ Mechanics=3 } },
        { item="Base.UnusableMetal",    uses=8, skills={ Mechanics=3 } },
      },
    },

    {
      name = "Fix Trailer Lids 1",
      require = {
        "Base.M101A3Cover1_Item",
        "Base.FRSideContainer1","Base.FRSideContainer2","Base.FRSideContainer3","Base.FRSideContainer8",
        "Base.FRSideContainer_RS1","Base.FRSideContainer_RS2","Base.FRSideContainer_RS3",
      },
      conditionModifier = 0.3,
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.Epoxy",          uses=2, skills={ Mechanics=2 } },
        { item="Base.Glue",           uses=4, skills={ Mechanics=2 } },
        { item="Base.DuctTape",       uses=4, skills={ Mechanics=2 }, successSound = "FixWithTape" },
        { item="Base.FiberglassTape", uses=2, skills={ Mechanics=2 }, successSound = "FixWithTape" },
        { item="Base.Zipties",        uses=4, skills={ Mechanics=2 } },
      },
    },

    {
      name = "Fix Hood Welding",
      require = {
        "Base.EngineDoor1","Base.EngineDoor2","Base.EngineDoor3","Base.EngineDoor8","Base.ECTO1EngineDoor1",
        "Base.SL500HardTop3","Base.W460EngineDoor2","Base.R32EngineDoor0","Base.R32EngineDoor3","Base.ATASamaraHood2Item3",
        "Base.ATASamaraHood3Item3","Base.McLarenF1Hood3","Base.E150EngineDoor2","Base.M35FrontHardTop2","Base.DG70RTEngineDoor",
        "Base.DG70PDEngineDoor","Base.DG70TAEngineDoor0","Base.DG70TAEngineDoor1","Base.fhqFusFleaSupHood","Base.NivaEngineDoor1",
        "Base.89BroncoEngineDoor2","Base.89BroncoBedCover","Base.88ChevyS10BedCover","Base.82JeepJ10BedCover",
        "Base.88ChevyS10EngineDoor2","Base.82JeepJ10EngineDoor2","Base.63beetleHPRoof0","Base.CadillacFuneralCoachHoodSC1",
        "Base.CadillacFleetwoodHoodSC1","Base.ChevyBlazerHoodSC2","Base.ChevyCamaroHoodSC3","Base.ChevyCapriceHoodSC1",
        "Base.ChevyG30HoodSC2","Base.ChevyP30HoodSC2","Base.ChevyCavalierHoodSC1","Base.FordBroncoHoodSC2","Base.FordCrownVictoriaHoodSC1",
        "Base.FordExplorerHoodSC2","Base.FordF150HoodSC2","Base.FordF700HoodSC2","Base.FordMustangHoodSC3","Base.HondaAccordHoodSC1",
        "Base.JeepCherokeeHoodSC2","Base.JeepCJ7HoodSC2","Base.M35Hood2","Base.MazdaB2000HoodSC2","Base.Mercedes280HoodSC1",
        "Base.PlymouthVoyagerHoodSC2","Base.ToyotaCamryHoodSC1","Base.VWRabbitHoodSC1","Base.Shubert38EngineDoor1","Base.ShubertSedanEngineDoor1",
        "Base.49powerWagonEngineDoor2","Base.ChevyC70HoodSC2","Base.FordTaurusHoodSC1","Base.GeoTrackerHoodSC2","Base.LassiterEngineDoor1",
        "Base.FuturaEngineDoor3","Base.CulverEngineDoor1","Base.PotomacEngineDoor1","Base.CUDAEngineDoorStock","Base.CUDAEngineDoor",
        "Base.CUDAEngineDoorAAR","Base.89trooperEngineDoor2","Base.93townCarEngineDoor1","Base.69miniEngineDoor1","Base.69miniEngineDoorBelts1",
        "Base.69miniEngineDoorPitbull1","Base.CivicEngineDoor1","Base.CytAstra89Hood1","Base.90fordF350EngineDoor2","Base.GrummanLLVHoodSC2",
        "Base.MackDM800HoodSC2","Base.ChevyG30HoodSC2","Base.92fordCVPIEngineDoor1","Base.93fordCF8000EngineDoor2","Base.113hEngineDoor1",
        "Base.CytMercEvoHood3","Base.99fordCVPIEngineDoor1","Base.DodgePowerWagonHoodSC2","Base.91rangeEngineDoor2","Base.1992fiorinoHood1",
        "Base.1990spazio147Hood1","Base.69camaroEngineDoorRS","Base.69camaroEngineDoorSS","Base.93mustangSSPEngineDoor1","Base.63beetleEngineDoor1",
        "Base.1990traficHood2","Base.91geoMetroEngineDoor1","Base.67gt500EngineDoor3","Base.67gt500eEngineDoor3","Base.89dodgeCaravanEngineDoor1",
        "Base.63Type2VanEngineDoor1","Base.87toyotaMR2EngineDoor3","Base.93fordF350EngineDoor2","Base.1988fuegoHood3","Base.1970fiat600Hood1",
        "Base.90bmwE30EngineDoor3","Base.87fordB700EngineDoor2","Base.93fordTaurusEngineDoor1","Base.1979rastrojeroHood2","Base.1978renault12Hood1",
        "Base.93chevySuburbanEngineDoor2","Base.88toyotaHiluxEngineDoor2","Base.86chevyCUCVEngineDoor2","Base.84jeepXJEngineDoor2",
        "Base.76chevyKseriesEngineDoor2","Base.76chevyK10BedCap2","Base.76chevyK20BedCap2","Base.76chevyK10OpenBedCap2","Base.76chevyK20OpenBedCap2",
        "Base.82porsche911turboEngineDoor3","Base.82porsche911RWBEngineDoor3","Base.85chevyCapriceEngineDoor1","Base.85pontiacParisienneEngineDoor1",
        "Base.85buickLeSabreEngineDoor1","Base.85oldsmobileDelta88EngineDoor1","Base.80chevyCKEngineDoor2","Base.91fordLTDEngineDoor1",
        "Base.87buickRegalEngineDoor3","Base.81deloreanDMC12EngineDoor3","Base.89volvo240EngineDoor1","Base.89volvo242EngineDoor1",
        "Base.66pontiacLeMansEngineDoor3","Base.66pontiacGTOEngineDoor3","Base.87chevySuburbanEngineDoor2","Base.68firebirdEngineDoor3",
        "Base.68firebirdRamAirEngineDoor3","Base.68firebirdRamAirCustomEngineDoor3","Base.77firebirdEngineDoor3","Base.77firebirdEngineDoorFR3",
        "Base.77firebirdEngineDoorTA3","Base.82firebirdEngineDoor3","Base.73fordFalconEngineDoor3","Base.73fordFalconPSEngineDoor3",
        "Base.04vwTouranEngineDoor1","Base.91nissan240sxEngineDoor3","Base.91fordRangerEngineDoor2","Base.91fordRangerBedCap2",
        "Base.65bansheeFinEngineDoor3","Base.65bansheeCowlEngineDoor3","Base.65bansheeMetalRoof3","Base.89defenderEngineDoor2",
        "Base.89defenderHardCover2","Base.98stageaEngineDoor3",
      },
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 1.0,
      equip = { primary = "Base.BlowTorch", wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallSheetMetal",  uses=4, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperSheet",      uses=2, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallCopperSheet", uses=4, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.GoldSheet",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SilverSheet",      uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SmallArmorPlate",  uses=3, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.MetalPipe",        uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.MetalBar",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.LeadPipe",         uses=1, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.AluminumScrap",    uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.BrassScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.CopperScrap",      uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.IronScrap",        uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.ScrapMetal",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.SteelScrap",       uses=8, skills={ MetalWelding=3, Mechanics=3 } },
        { item="Base.UnusableMetal",    uses=8, skills={ MetalWelding=3, Mechanics=3 } },
      },
    },

    {
      name = "Fix Hood",
      require = {
        "Base.EngineDoor1","Base.EngineDoor2","Base.EngineDoor3","Base.EngineDoor8","Base.ECTO1EngineDoor1",
        "Base.SL500HardTop3","Base.W460EngineDoor2","Base.R32EngineDoor0","Base.R32EngineDoor3","Base.ATASamaraHood2Item3",
        "Base.ATASamaraHood3Item3","Base.McLarenF1Hood3","Base.E150EngineDoor2","Base.M35FrontHardTop2","Base.DG70RTEngineDoor",
        "Base.DG70PDEngineDoor","Base.DG70TAEngineDoor0","Base.DG70TAEngineDoor1","Base.fhqFusFleaSupHood","Base.NivaEngineDoor1",
        "Base.89BroncoEngineDoor2","Base.89BroncoBedCover","Base.88ChevyS10BedCover","Base.82JeepJ10BedCover",
        "Base.88ChevyS10EngineDoor2","Base.82JeepJ10EngineDoor2","Base.63beetleHPRoof0","Base.CadillacFuneralCoachHoodSC1",
        "Base.CadillacFleetwoodHoodSC1","Base.ChevyBlazerHoodSC2","Base.ChevyCamaroHoodSC3","Base.ChevyCapriceHoodSC1",
        "Base.ChevyG30HoodSC2","Base.ChevyP30HoodSC2","Base.ChevyCavalierHoodSC1","Base.FordBroncoHoodSC2","Base.FordCrownVictoriaHoodSC1",
        "Base.FordExplorerHoodSC2","Base.FordF150HoodSC2","Base.FordF700HoodSC2","Base.FordMustangHoodSC3","Base.HondaAccordHoodSC1",
        "Base.JeepCherokeeHoodSC2","Base.JeepCJ7HoodSC2","Base.M35Hood2","Base.MazdaB2000HoodSC2","Base.Mercedes280HoodSC1",
        "Base.PlymouthVoyagerHoodSC2","Base.ToyotaCamryHoodSC1","Base.VWRabbitHoodSC1","Base.Shubert38EngineDoor1","Base.ShubertSedanEngineDoor1",
        "Base.49powerWagonEngineDoor2","Base.ChevyC70HoodSC2","Base.FordTaurusHoodSC1","Base.GeoTrackerHoodSC2","Base.LassiterEngineDoor1",
        "Base.FuturaEngineDoor3","Base.CulverEngineDoor1","Base.PotomacEngineDoor1","Base.CUDAEngineDoorStock","Base.CUDAEngineDoor",
        "Base.CUDAEngineDoorAAR","Base.89trooperEngineDoor2","Base.93townCarEngineDoor1","Base.69miniEngineDoor1","Base.69miniEngineDoorBelts1",
        "Base.69miniEngineDoorPitbull1","Base.CivicEngineDoor1","Base.CytAstra89Hood1","Base.90fordF350EngineDoor2","Base.GrummanLLVHoodSC2",
        "Base.MackDM800HoodSC2","Base.ChevyG30HoodSC2","Base.92fordCVPIEngineDoor1","Base.93fordCF8000EngineDoor2","Base.113hEngineDoor1",
        "Base.CytMercEvoHood3","Base.99fordCVPIEngineDoor1","Base.DodgePowerWagonHoodSC2","Base.91rangeEngineDoor2","Base.1992fiorinoHood1",
        "Base.1990spazio147Hood1","Base.69camaroEngineDoorRS","Base.69camaroEngineDoorSS","Base.93mustangSSPEngineDoor1","Base.63beetleEngineDoor1",
        "Base.1990traficHood2","Base.91geoMetroEngineDoor1","Base.67gt500EngineDoor3","Base.67gt500eEngineDoor3","Base.89dodgeCaravanEngineDoor1",
        "Base.63Type2VanEngineDoor1","Base.87toyotaMR2EngineDoor3","Base.93fordF350EngineDoor2","Base.1988fuegoHood3","Base.1970fiat600Hood1",
        "Base.90bmwE30EngineDoor3","Base.87fordB700EngineDoor2","Base.93fordTaurusEngineDoor1","Base.1979rastrojeroHood2","Base.1978renault12Hood1",
        "Base.93chevySuburbanEngineDoor2","Base.88toyotaHiluxEngineDoor2","Base.86chevyCUCVEngineDoor2","Base.84jeepXJEngineDoor2",
        "Base.76chevyKseriesEngineDoor2","Base.76chevyK10BedCap2","Base.76chevyK20BedCap2","Base.76chevyK10OpenBedCap2","Base.76chevyK20OpenBedCap2",
        "Base.82porsche911turboEngineDoor3","Base.82porsche911RWBEngineDoor3","Base.85chevyCapriceEngineDoor1","Base.85pontiacParisienneEngineDoor1",
        "Base.85buickLeSabreEngineDoor1","Base.85oldsmobileDelta88EngineDoor1","Base.80chevyCKEngineDoor2","Base.91fordLTDEngineDoor1",
        "Base.87buickRegalEngineDoor3","Base.81deloreanDMC12EngineDoor3","Base.89volvo240EngineDoor1","Base.89volvo242EngineDoor1",
        "Base.66pontiacLeMansEngineDoor3","Base.66pontiacGTOEngineDoor3","Base.87chevySuburbanEngineDoor2","Base.68firebirdEngineDoor3",
        "Base.68firebirdRamAirEngineDoor3","Base.68firebirdRamAirCustomEngineDoor3","Base.77firebirdEngineDoor3","Base.77firebirdEngineDoorFR3",
        "Base.77firebirdEngineDoorTA3","Base.82firebirdEngineDoor3","Base.73fordFalconEngineDoor3","Base.73fordFalconPSEngineDoor3",
        "Base.04vwTouranEngineDoor1","Base.91nissan240sxEngineDoor3","Base.91fordRangerEngineDoor2","Base.91fordRangerBedCap2",
        "Base.65bansheeFinEngineDoor3","Base.65bansheeCowlEngineDoor3","Base.65bansheeMetalRoof3","Base.89defenderEngineDoor2",
        "Base.89defenderHardCover2","Base.98stageaEngineDoor3",
      },
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.5,
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=2, skills={ Mechanics=3 } },
        { item="Base.SmallSheetMetal",  uses=4, skills={ Mechanics=3 } },
        { item="Base.CopperSheet",      uses=2, skills={ Mechanics=3 } },
        { item="Base.SmallCopperSheet", uses=4, skills={ Mechanics=3 } },
        { item="Base.GoldSheet",        uses=1, skills={ Mechanics=3 } },
        { item="Base.SilverSheet",      uses=1, skills={ Mechanics=3 } },
        { item="Base.SmallArmorPlate",  uses=3, skills={ Mechanics=3 } },
        { item="Base.MetalPipe",        uses=1, skills={ Mechanics=3 } },
        { item="Base.MetalBar",         uses=1, skills={ Mechanics=3 } },
        { item="Base.LeadPipe",         uses=1, skills={ Mechanics=3 } },
        { item="Base.Plank",            uses=4, skills={ Woodwork=3, Mechanics=3 } },
        { item="Base.AluminumScrap",    uses=8, skills={ Mechanics=3 } },
        { item="Base.BrassScrap",       uses=8, skills={ Mechanics=3 } },
        { item="Base.CopperScrap",      uses=8, skills={ Mechanics=3 } },
        { item="Base.IronScrap",        uses=8, skills={ Mechanics=3 } },
        { item="Base.ScrapMetal",       uses=8, skills={ Mechanics=3 } },
        { item="Base.SteelScrap",       uses=8, skills={ Mechanics=3 } },
        { item="Base.UnusableMetal",    uses=8, skills={ Mechanics=3 } },
      },
    },

    {
      name = "Fix Military Hood Welding",
      require = {
        "Base.EngineM113Door8","Base.67commandoEngineDoor2","Base.92amgeneralM998EngineDoor2","Base.M12EngineDoor2","Base.EngineM113Door1",
        "Base.EngineM113Door2","Base.EngineM113Door3","Base.M151A2EngineDoor2","Base.M35A2EngineDoor2","Base.M923EngineDoor2","Base.M923HardCover1",
        "Base.Int4700Hood2","Base.P19AEngineDoor2","Base.U1550LHood2","Base.97BushEngineDoor2","Base.M911EngineDoor2","Base.90pierceArrowEngineDoor2",
        "Base.HMMWVHoodSC2","Base.93chevySuburbanFrontWindowArmor","Base.93chevySuburbanRearWindowArmor","Base.93chevySuburbanBackWindowArmor",
        "Base.93chevySuburbanWindshieldArmor","Base.93chevySuburbanWindshieldRearArmor","Base.88toyotaHiluxWindshieldArmor",
        "Base.88toyotaHiluxFrontWindowArmor","Base.88toyotaHiluxBackWindowArmor","Base.88toyotaHiluxWindshieldRearArmor","Base.86chevyCUCVFrontWindowArmor",
        "Base.86chevyCUCVBackWindowArmor","Base.86chevyCUCVWindshieldArmor","Base.86chevyCUCVWindshieldRearArmor","Base.86chevyM1010WindshieldRearArmor",
        "Base.84jeepXJFrontWindowArmor","Base.84jeepXJRearWindowArmor","Base.84jeepXJBackWindowArmor","Base.84jeepXJWindshieldArmor",
        "Base.84jeepXJWindshieldRearArmor","Base.76chevyKseriesFrontWindowArmor","Base.76chevyKseriesWindshieldArmor","Base.82porsche911FrontWindowArmor",
        "Base.82porsche911RearWindowArmor","Base.82porsche911WindshieldArmor","Base.82porsche911WindshieldRearArmor","Base.85gmBbodyWindshieldArmorM",
        "Base.85gmBbodyFrontWindowArmorM","Base.85gmBbodyRearWindowArmorM","Base.85gmBbodyWindshieldRearArmorM","Base.91fordLTDWagonBackWindowArmor",
        "Base.91fordLTDWagonWindshieldRearArmor","Base.87buickRegalWindshieldArmor","Base.87buickRegalFrontWindowArmor","Base.87buickRegalRearWindowArmor",
        "Base.87buickRegalWindshieldRearArmor","Base.81deloreanDMC12WindshieldArmor","Base.81deloreanDMC12FrontWindowArmor","Base.81deloreanDMC12RearWindowArmor",
        "Base.81deloreanDMC12RearCover","Base.89volvo240WindshieldArmorM","Base.89volvo240FrontWindowArmorM","Base.89volvo240RearWindowArmorM",
        "Base.89volvo245WagonBackWindowArmorM","Base.89volvo244SedanBackWindowArmorM","Base.89volvo240WindshieldRearArmorM","Base.89volvo240Louver1",
        "Base.66pontiacLeMansWindshieldArmor","Base.66pontiacLeMansFrontWindowArmor","Base.66pontiacLeMansWindshieldRearArmor","Base.87chevySuburbanFrontWindowArmor",
        "Base.87chevySuburbanRearWindowArmor","Base.87chevySuburbanBackWindowArmor","Base.87chevySuburbanWindshieldArmor","Base.87chevySuburbanWindshieldRearArmor",
        "Base.utilityBoxWindshieldRearArmor","Base.80manKat1FrontWindowArmor","Base.80manKat1WindshieldArmor","Base.80manKat1EngineDoor2",
        "Base.68firebirdWindshieldArmor","Base.68firebirdFrontWindowArmor","Base.68firebirdWindshieldRearArmor","Base.77firebirdWindshieldArmor",
        "Base.77firebirdFrontWindowArmor","Base.77firebirdWindshieldRearArmor","Base.82firebirdWindshieldArmor","Base.82firebirdFrontWindowArmor",
        "Base.82firebirdWindshieldRearArmor","Base.73fordFalconWindshieldArmor","Base.73fordFalconFrontWindowArmor","Base.73fordFalconRearWindowArmor",
        "Base.73fordFalconWindshieldRearArmor","Base.04vwTouranFrontWindowArmor","Base.04vwTouranRearWindowArmor","Base.04vwTouranBackWindowArmor",
        "Base.04vwTouranWindshieldArmor","Base.04vwTouranWindshieldRearArmor","Base.87fordF700WindowFrontArmor","Base.87fordF700WindshieldArmor",
        "Base.91nissan240sxWindshieldArmor","Base.91nissan240sxFrontWindowArmor","Base.91nissan240sxRearWindowArmor","Base.91nissan240sxWindshieldRearArmor",
        "Base.91fordRangerWindshieldArmor","Base.91fordRangerFrontWindowArmor","Base.91fordRangerBackWindowArmor","Base.65bansheeWindshieldArmor",
        "Base.65bansheeFrontWindowArmor","Base.65bansheeWindshieldRearArmor","Base.89defenderWindshieldArmor","Base.89defenderFrontWindowArmor",
        "Base.89defenderRearWindowArmor","Base.89defenderBackWindowArmor","Base.89defenderWindshieldRearArmor","Base.98stageaWindshieldArmor",
        "Base.98stageaFrontWindowArmor","Base.98stageaRearWindowArmor","Base.98stageaBackWindowArmor","Base.98stageaWindshieldRearArmor",
        "Base.PotomacFrontArmor","Base.PotomacFrontLeftWindowArmor","Base.PotomacFrontRightWindowArmor","Base.PotomacRearLeftWindowArmor",
        "Base.PotomacRearRightWindowArmor","Base.PotomacWindshieldArmor","Base.PotomacWindshieldRearArmor","Base.DeathMustangRearWindshield3",
        "Base.DeathMustangWindshield3","Base.DeathMustangHood3","Base.DeathMustangFrontWindow3","Base.DeathMustangRearWindow3","Base.DeathMustangDoor3",
        "Base.M911CarFrontDoorArmor","Base.M911WindshieldArmor","Base.M911WindshieldRearArmor","Base.ShubertSedanFrontArmor","Base.ShubertSedanFrontLeftWindowArmor",
        "Base.ShubertSedanFrontRightWindowArmor","Base.ShubertSedanRearLeftWindowArmor","Base.ShubertSedanRearRightWindowArmor","Base.ShubertSedanWindshieldArmor",
        "Base.ShubertSedanWindshieldRearArmor","Base.R32WindshieldArmor","Base.R32WindshieldRearArmor","Base.R32RearWindowArmor","Base.ECTO1WindshieldArmor",
        "Base.ECTO1WindshieldRearArmor","Base.ATA_Bus_Protection_windows_left_Item","Base.ATA_Bus_Protection_windows_right_Item","Base.ATA_Bus_Protection_windows_front_Item",
        "Base.ATA_Bus_Protection_door_rear_Item","Base.ATA_Bus_Protection_door_Item","Base.M151A2WindshieldArmor1_Item","Base.M151A2CabArmor1_Item",
        "Base.M151A2BarrierLeft1_Item","Base.M151A2BarrierRight1_Item","Base.92amgeneralM998FrontArmor","Base.92amgeneralM998RearArmor","Base.92amgeneralM998WindshieldArmor0",
        "Base.92amgeneralM998WindshieldArmor1","Base.TankGasTank1","Base.TankGasTank2","Base.TankGasTank3","Base.M35A2WindshieldArmor1","Base.M35A2DoorArmor1",
        "Base.W460WindshieldArmor1","Base.W460CarFrontDoorArmor1","Base.W460CarRearDoorArmor1","Base.W460CarBackWindowArmor1","Base.W460WindshieldRearArmor1",
        "Base.W460WindshieldRearArmorM","Base.W460Guards","Base.SCInteriorArmory","Base.M923WindshieldArmor1","Base.M923DoorArmor1","Base.M923GuntruckArmor1",
        "Base.FJ75WindshieldArmor2","Base.FJ75DoorArmor2","Base.P19ACarFrontDoorArmor","Base.P19AWindshieldArmor","Base.U1550LInteriorArmoring2","Base.U1550LWindshieldBars2",
        "Base.U1550LWindowArmor2","Base.R32BumperA","Base.R32BumperRearA","Base.R32SideskirtsA","Base.R32DoorArmor","Base.ATAMustangProtectionWindowLeftItem",
        "Base.ATAMustangProtectionWindowRightItem","Base.ATAMustangProtectionWindowLeftItem","Base.ATAMustangProtectionWindowRightItem","Base.ATAMustangProtectionWindowFrontItem",
        "Base.ATAMustangProtectionWindowRearItem","Base.ATAMustangProtectionWindowRearItem","Base.McLarenF1WindowArmor3","Base.E150WindshieldArmor","Base.E150WindshieldRearArmor",
        "Base.E150DoorArmor","Base.E150WindowRearArmor","Base.DG70WindshieldArmor","Base.DG70WindshieldRearArmor","Base.DG70DoorArmor","Base.80sPickupWindowFrontArmor",
        "Base.80sPickupWindshieldArmor","Base.80sPickupWindowRearArmor","Base.FireCoachWindshieldArmor2","Base.FireCoachWindowArmor2","Base.FireCoachDoorArmor2",
        "Base.FordMustangDoorArmorSC3","Base.FordMustangWindshieldArmorSC3","Base.FordMustangWindowArmorSC3","Base.BallisticGlassWindshieldSC2","Base.BallisticGlassWindowSC2",
        "Base.JeepCherokeeDoorArmor2","Base.JeepCherokeeWindshieldArmor2","Base.JeepCherokeeWindowArmor2","Base.M35WindowArmor2","Base.M35DoorArmor2","Base.M35WindshieldArmor2",
        "Base.49powerWagonFrontDoorArmor","Base.49powerWagonRearDoorArmor","Base.49powerWagonWindshieldArmor","Base.49powerWagonWindshieldRearArmor","Base.CUDAWindshieldArmor",
        "Base.CUDAWindshieldRearArmor","Base.CUDADoorArmor","Base.MH_MkII_railgun1","Base.MH_MkII_railgun2","Base.MH_MkII_railgun3","Base.MH_MkII_railgunshelf1",
        "Base.MH_MkII_railgunshelf2","Base.MH_MkII_railgunshelf3","Base.89trooperFrontDoorArmor","Base.89trooperRearDoorArmor","Base.89trooperWindshieldArmor",
        "Base.89trooperWindshieldRearArmor","Base.89trooperBackWindowArmor","Base.93townCarFrontDoorArmor","Base.93townCarRearDoorArmor","Base.93townCarWindshieldArmorA",
        "Base.93townCarWindshieldArmorB","Base.93townCarWindshieldRearArmor","Base.93townCarMiddleWindowArmor","Base.69miniFrontDoorArmor","Base.69miniRearWindowArmor",
        "Base.69miniWindshieldArmor","Base.69miniWindshieldRearArmor","Base.90pierceArrowSideWindowArmor","Base.90pierceArrowWindshieldArmor","Base.90pierceArrowWindshieldRearArmor",
        "Base.CytAstra89WindowArmor1","Base.CytAstra89WindshieldBars1","Base.CytAstra89DoorArmor1","Base.CytAstra89WindowBackArmor1","Base.CytAstra89RearWindArmor1",
        "Base.90fordF350ambWindshieldArmor","Base.90fordF350ambWindowFrontArmor","Base.90fordF350ambWindowRearArmor","Base.90fordF350ambWindshieldRearArmor",
        "Base.fordCVPIWindshieldArmor","Base.fordCVPIFrontWindowArmor","Base.fordCVPIRearWindowArmor","Base.fordCVPIWindshieldRearArmor","Base.CytMercEvoWindowArmor3",
        "Base.CytMercEvoWindowBackArmor3","Base.CytMercEvoRearWindArmor3","Base.CytMercEvoWindshieldBars3","Base.fordCVPIWindshieldArmor","Base.fordCVPIFrontWindowArmor",
        "Base.fordCVPIRearWindowArmor","Base.fordCVPIWindshieldRearArmor","Base.91rangeFrontWindowArmor","Base.91rangeRearWindowArmor","Base.91rangeWindshieldArmor",
        "Base.91rangeWindshieldRearArmor","Base.ShermanTurret2","Base.69camaroWindshieldArmor","Base.69camaroWindshieldRearArmor","Base.69camaroWindowArmor",
        "Base.93mustangSSPWindshieldArmor","Base.93mustangSSPFrontWindowArmor","Base.93mustangSSPRearWindowArmor","Base.93mustangSSPWindshieldRearArmor",
        "Base.63beetleFrontWindowArmor","Base.63beetleRearWindowArmor","Base.63beetleWindshieldArmor","Base.63beetleWindshieldRearArmor","Base.67gt500WindshieldArmor",
        "Base.67gt500WindshieldRearArmor","Base.67gt500WindowArmor","Base.89dodgeCaravanFrontWindowArmor","Base.89dodgeCaravanRearWindowArmor","Base.89dodgeCaravanBackWindowArmor",
        "Base.89dodgeCaravanWindshieldArmor","Base.89dodgeCaravanWindshieldRearArmor","Base.63Type2VanFrontWindowArmor","Base.63Type2VanRearWindowArmor",
        "Base.63Type2VanDoubleRearWindowArmor","Base.63Type2VanWindshieldArmor","Base.63Type2VanWindshieldRearArmor","Base.87toyotaMR2WindshieldArmor","Base.87toyotaMR2WindowArmor",
        "Base.87toyotaMR2WindshieldRearArmor","Base.93fordF350FrontWindowArmor","Base.93fordF350RearWindowArmor","Base.93fordF350WindshieldArmor","Base.93fordF350utilityWindshieldRearArmor",
        "Base.90bmwE30WindshieldArmor","Base.90bmwE30FrontWindowArmor","Base.90bmwE30CabrioWindowArmor","Base.90bmwE30SedanRearWindowArmor","Base.90bmwE30TouringRearWindowArmor",
        "Base.90bmwE30TouringBackWindowArmor","Base.90bmwE30WindshieldRearArmor","Base.87fordB700SideArmor","Base.87fordB700SideArmorPrison","Base.87fordB700DoubleDoorArmor",
        "Base.87fordB700WindshieldArmor","Base.87fordB700LargeSideArmor","Base.87fordB700LargeSideArmorPrison","Base.87fordB700RearArmor","Base.93fordTaurusWindshieldArmor",
        "Base.93fordTaurusFrontWindowArmor","Base.93fordTaurusRearWindowArmor","Base.93fordTaurusWagonBackWindowArmor","Base.93fordTaurusSedanWindshieldRearArmor",
        "Base.93fordTaurusWagonWindshieldRearArmor",
      },
      globalItem = { item = "Base.BlowTorch", uses = 4, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=3,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.SmallSheetMetal",  uses=6,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.CopperSheet",      uses=3,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.SmallCopperSheet", uses=6,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.GoldSheet",        uses=2,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.SilverSheet",      uses=2,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.SmallArmorPlate",  uses=4,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.MetalPipe",        uses=2,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.MetalBar",         uses=2,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.LeadPipe",         uses=4,  skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.AluminumScrap",    uses=12, skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.BrassScrap",       uses=12, skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.CopperScrap",      uses=12, skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.IronScrap",        uses=12, skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.ScrapMetal",       uses=12, skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.SteelScrap",       uses=12, skills={ MetalWelding=4, Mechanics=4 } },
        { item="Base.UnusableMetal",    uses=12, skills={ MetalWelding=4, Mechanics=4 } },
      },
    },

    {
      name = "Fix Military Hood",
      require = {
        "Base.EngineM113Door8","Base.67commandoEngineDoor2","Base.92amgeneralM998EngineDoor2","Base.M12EngineDoor2","Base.EngineM113Door1",
        "Base.EngineM113Door2","Base.EngineM113Door3","Base.M151A2EngineDoor2","Base.M35A2EngineDoor2","Base.M923EngineDoor2","Base.M923HardCover1",
        "Base.Int4700Hood2","Base.P19AEngineDoor2","Base.U1550LHood2","Base.97BushEngineDoor2","Base.M911EngineDoor2","Base.90pierceArrowEngineDoor2",
        "Base.HMMWVHoodSC2","Base.93chevySuburbanFrontWindowArmor","Base.93chevySuburbanRearWindowArmor","Base.93chevySuburbanBackWindowArmor",
        "Base.93chevySuburbanWindshieldArmor","Base.93chevySuburbanWindshieldRearArmor","Base.88toyotaHiluxWindshieldArmor",
        "Base.88toyotaHiluxFrontWindowArmor","Base.88toyotaHiluxBackWindowArmor","Base.88toyotaHiluxWindshieldRearArmor","Base.86chevyCUCVFrontWindowArmor",
        "Base.86chevyCUCVBackWindowArmor","Base.86chevyCUCVWindshieldArmor","Base.86chevyCUCVWindshieldRearArmor","Base.86chevyM1010WindshieldRearArmor",
        "Base.84jeepXJFrontWindowArmor","Base.84jeepXJRearWindowArmor","Base.84jeepXJBackWindowArmor","Base.84jeepXJWindshieldArmor",
        "Base.84jeepXJWindshieldRearArmor","Base.76chevyKseriesFrontWindowArmor","Base.76chevyKseriesWindshieldArmor","Base.82porsche911FrontWindowArmor",
        "Base.82porsche911RearWindowArmor","Base.82porsche911WindshieldArmor","Base.82porsche911WindshieldRearArmor","Base.85gmBbodyWindshieldArmorM",
        "Base.85gmBbodyFrontWindowArmorM","Base.85gmBbodyRearWindowArmorM","Base.85gmBbodyWindshieldRearArmorM","Base.91fordLTDWagonBackWindowArmor",
        "Base.91fordLTDWagonWindshieldRearArmor","Base.87buickRegalWindshieldArmor","Base.87buickRegalFrontWindowArmor","Base.87buickRegalRearWindowArmor",
        "Base.87buickRegalWindshieldRearArmor","Base.81deloreanDMC12WindshieldArmor","Base.81deloreanDMC12FrontWindowArmor","Base.81deloreanDMC12RearWindowArmor",
        "Base.81deloreanDMC12RearCover","Base.89volvo240WindshieldArmorM","Base.89volvo240FrontWindowArmorM","Base.89volvo240RearWindowArmorM",
        "Base.89volvo245WagonBackWindowArmorM","Base.89volvo244SedanBackWindowArmorM","Base.89volvo240WindshieldRearArmorM","Base.89volvo240Louver1",
        "Base.66pontiacLeMansWindshieldArmor","Base.66pontiacLeMansFrontWindowArmor","Base.66pontiacLeMansWindshieldRearArmor","Base.87chevySuburbanFrontWindowArmor",
        "Base.87chevySuburbanRearWindowArmor","Base.87chevySuburbanBackWindowArmor","Base.87chevySuburbanWindshieldArmor","Base.87chevySuburbanWindshieldRearArmor",
        "Base.utilityBoxWindshieldRearArmor","Base.80manKat1FrontWindowArmor","Base.80manKat1WindshieldArmor","Base.80manKat1EngineDoor2",
        "Base.68firebirdWindshieldArmor","Base.68firebirdFrontWindowArmor","Base.68firebirdWindshieldRearArmor","Base.77firebirdWindshieldArmor",
        "Base.77firebirdFrontWindowArmor","Base.77firebirdWindshieldRearArmor","Base.82firebirdWindshieldArmor","Base.82firebirdFrontWindowArmor",
        "Base.82firebirdWindshieldRearArmor","Base.73fordFalconWindshieldArmor","Base.73fordFalconFrontWindowArmor","Base.73fordFalconRearWindowArmor",
        "Base.73fordFalconWindshieldRearArmor","Base.04vwTouranFrontWindowArmor","Base.04vwTouranRearWindowArmor","Base.04vwTouranBackWindowArmor",
        "Base.04vwTouranWindshieldArmor","Base.04vwTouranWindshieldRearArmor","Base.87fordF700WindowFrontArmor","Base.87fordF700WindshieldArmor",
        "Base.91nissan240sxWindshieldArmor","Base.91nissan240sxFrontWindowArmor","Base.91nissan240sxRearWindowArmor","Base.91nissan240sxWindshieldRearArmor",
        "Base.91fordRangerWindshieldArmor","Base.91fordRangerFrontWindowArmor","Base.91fordRangerBackWindowArmor","Base.65bansheeWindshieldArmor",
        "Base.65bansheeFrontWindowArmor","Base.65bansheeWindshieldRearArmor","Base.89defenderWindshieldArmor","Base.89defenderFrontWindowArmor",
        "Base.89defenderRearWindowArmor","Base.89defenderBackWindowArmor","Base.89defenderWindshieldRearArmor","Base.98stageaWindshieldArmor",
        "Base.98stageaFrontWindowArmor","Base.98stageaRearWindowArmor","Base.98stageaBackWindowArmor","Base.98stageaWindshieldRearArmor",
        "Base.PotomacFrontArmor","Base.PotomacFrontLeftWindowArmor","Base.PotomacFrontRightWindowArmor","Base.PotomacRearLeftWindowArmor",
        "Base.PotomacRearRightWindowArmor","Base.PotomacWindshieldArmor","Base.PotomacWindshieldRearArmor","Base.DeathMustangRearWindshield3",
        "Base.DeathMustangWindshield3","Base.DeathMustangHood3","Base.DeathMustangFrontWindow3","Base.DeathMustangRearWindow3","Base.DeathMustangDoor3",
        "Base.M911CarFrontDoorArmor","Base.M911WindshieldArmor","Base.M911WindshieldRearArmor","Base.ShubertSedanFrontArmor","Base.ShubertSedanFrontLeftWindowArmor",
        "Base.ShubertSedanFrontRightWindowArmor","Base.ShubertSedanRearLeftWindowArmor","Base.ShubertSedanRearRightWindowArmor","Base.ShubertSedanWindshieldArmor",
        "Base.ShubertSedanWindshieldRearArmor","Base.R32WindshieldArmor","Base.R32WindshieldRearArmor","Base.R32RearWindowArmor","Base.ECTO1WindshieldArmor",
        "Base.ECTO1WindshieldRearArmor","Base.ATA_Bus_Protection_windows_left_Item","Base.ATA_Bus_Protection_windows_right_Item","Base.ATA_Bus_Protection_windows_front_Item",
        "Base.ATA_Bus_Protection_door_rear_Item","Base.ATA_Bus_Protection_door_Item","Base.M151A2WindshieldArmor1_Item","Base.M151A2CabArmor1_Item",
        "Base.M151A2BarrierLeft1_Item","Base.M151A2BarrierRight1_Item","Base.92amgeneralM998FrontArmor","Base.92amgeneralM998RearArmor","Base.92amgeneralM998WindshieldArmor0",
        "Base.92amgeneralM998WindshieldArmor1","Base.TankGasTank1","Base.TankGasTank2","Base.TankGasTank3","Base.M35A2WindshieldArmor1","Base.M35A2DoorArmor1",
        "Base.W460WindshieldArmor1","Base.W460CarFrontDoorArmor1","Base.W460CarRearDoorArmor1","Base.W460CarBackWindowArmor1","Base.W460WindshieldRearArmor1",
        "Base.W460WindshieldRearArmorM","Base.W460Guards","Base.SCInteriorArmory","Base.M923WindshieldArmor1","Base.M923DoorArmor1","Base.M923GuntruckArmor1",
        "Base.FJ75WindshieldArmor2","Base.FJ75DoorArmor2","Base.P19ACarFrontDoorArmor","Base.P19AWindshieldArmor","Base.U1550LInteriorArmoring2","Base.U1550LWindshieldBars2",
        "Base.U1550LWindowArmor2","Base.R32BumperA","Base.R32BumperRearA","Base.R32SideskirtsA","Base.R32DoorArmor","Base.ATAMustangProtectionWindowLeftItem",
        "Base.ATAMustangProtectionWindowRightItem","Base.ATAMustangProtectionWindowLeftItem","Base.ATAMustangProtectionWindowRightItem","Base.ATAMustangProtectionWindowFrontItem",
        "Base.ATAMustangProtectionWindowRearItem","Base.ATAMustangProtectionWindowRearItem","Base.McLarenF1WindowArmor3","Base.E150WindshieldArmor","Base.E150WindshieldRearArmor",
        "Base.E150DoorArmor","Base.E150WindowRearArmor","Base.DG70WindshieldArmor","Base.DG70WindshieldRearArmor","Base.DG70DoorArmor","Base.80sPickupWindowFrontArmor",
        "Base.80sPickupWindshieldArmor","Base.80sPickupWindowRearArmor","Base.FireCoachWindshieldArmor2","Base.FireCoachWindowArmor2","Base.FireCoachDoorArmor2",
        "Base.FordMustangDoorArmorSC3","Base.FordMustangWindshieldArmorSC3","Base.FordMustangWindowArmorSC3","Base.BallisticGlassWindshieldSC2","Base.BallisticGlassWindowSC2",
        "Base.JeepCherokeeDoorArmor2","Base.JeepCherokeeWindshieldArmor2","Base.JeepCherokeeWindowArmor2","Base.M35WindowArmor2","Base.M35DoorArmor2","Base.M35WindshieldArmor2",
        "Base.49powerWagonFrontDoorArmor","Base.49powerWagonRearDoorArmor","Base.49powerWagonWindshieldArmor","Base.49powerWagonWindshieldRearArmor","Base.CUDAWindshieldArmor",
        "Base.CUDAWindshieldRearArmor","Base.CUDADoorArmor","Base.MH_MkII_railgun1","Base.MH_MkII_railgun2","Base.MH_MkII_railgun3","Base.MH_MkII_railgunshelf1",
        "Base.MH_MkII_railgunshelf2","Base.MH_MkII_railgunshelf3","Base.89trooperFrontDoorArmor","Base.89trooperRearDoorArmor","Base.89trooperWindshieldArmor",
        "Base.89trooperWindshieldRearArmor","Base.89trooperBackWindowArmor","Base.93townCarFrontDoorArmor","Base.93townCarRearDoorArmor","Base.93townCarWindshieldArmorA",
        "Base.93townCarWindshieldArmorB","Base.93townCarWindshieldRearArmor","Base.93townCarMiddleWindowArmor","Base.69miniFrontDoorArmor","Base.69miniRearWindowArmor",
        "Base.69miniWindshieldArmor","Base.69miniWindshieldRearArmor","Base.90pierceArrowSideWindowArmor","Base.90pierceArrowWindshieldArmor","Base.90pierceArrowWindshieldRearArmor",
        "Base.CytAstra89WindowArmor1","Base.CytAstra89WindshieldBars1","Base.CytAstra89DoorArmor1","Base.CytAstra89WindowBackArmor1","Base.CytAstra89RearWindArmor1",
        "Base.90fordF350ambWindshieldArmor","Base.90fordF350ambWindowFrontArmor","Base.90fordF350ambWindowRearArmor","Base.90fordF350ambWindshieldRearArmor",
        "Base.fordCVPIWindshieldArmor","Base.fordCVPIFrontWindowArmor","Base.fordCVPIRearWindowArmor","Base.fordCVPIWindshieldRearArmor","Base.CytMercEvoWindowArmor3",
        "Base.CytMercEvoWindowBackArmor3","Base.CytMercEvoRearWindArmor3","Base.CytMercEvoWindshieldBars3","Base.fordCVPIWindshieldArmor","Base.fordCVPIFrontWindowArmor",
        "Base.fordCVPIRearWindowArmor","Base.fordCVPIWindshieldRearArmor","Base.91rangeFrontWindowArmor","Base.91rangeRearWindowArmor","Base.91rangeWindshieldArmor",
        "Base.91rangeWindshieldRearArmor","Base.ShermanTurret2","Base.69camaroWindshieldArmor","Base.69camaroWindshieldRearArmor","Base.69camaroWindowArmor",
        "Base.93mustangSSPWindshieldArmor","Base.93mustangSSPFrontWindowArmor","Base.93mustangSSPRearWindowArmor","Base.93mustangSSPWindshieldRearArmor",
        "Base.63beetleFrontWindowArmor","Base.63beetleRearWindowArmor","Base.63beetleWindshieldArmor","Base.63beetleWindshieldRearArmor","Base.67gt500WindshieldArmor",
        "Base.67gt500WindshieldRearArmor","Base.67gt500WindowArmor","Base.89dodgeCaravanFrontWindowArmor","Base.89dodgeCaravanRearWindowArmor","Base.89dodgeCaravanBackWindowArmor",
        "Base.89dodgeCaravanWindshieldArmor","Base.89dodgeCaravanWindshieldRearArmor","Base.63Type2VanFrontWindowArmor","Base.63Type2VanRearWindowArmor",
        "Base.63Type2VanDoubleRearWindowArmor","Base.63Type2VanWindshieldArmor","Base.63Type2VanWindshieldRearArmor","Base.87toyotaMR2WindshieldArmor","Base.87toyotaMR2WindowArmor",
        "Base.87toyotaMR2WindshieldRearArmor","Base.93fordF350FrontWindowArmor","Base.93fordF350RearWindowArmor","Base.93fordF350WindshieldArmor","Base.93fordF350utilityWindshieldRearArmor",
        "Base.90bmwE30WindshieldArmor","Base.90bmwE30FrontWindowArmor","Base.90bmwE30CabrioWindowArmor","Base.90bmwE30SedanRearWindowArmor","Base.90bmwE30TouringRearWindowArmor",
        "Base.90bmwE30TouringBackWindowArmor","Base.90bmwE30WindshieldRearArmor","Base.87fordB700SideArmor","Base.87fordB700SideArmorPrison","Base.87fordB700DoubleDoorArmor",
        "Base.87fordB700WindshieldArmor","Base.87fordB700LargeSideArmor","Base.87fordB700LargeSideArmorPrison","Base.87fordB700RearArmor","Base.93fordTaurusWindshieldArmor",
        "Base.93fordTaurusFrontWindowArmor","Base.93fordTaurusRearWindowArmor","Base.93fordTaurusWagonBackWindowArmor","Base.93fordTaurusSedanWindshieldRearArmor",
        "Base.93fordTaurusWagonWindshieldRearArmor",
      },
      globalItem = { item = "Base.Screws", uses = 16, consume = true },
      conditionModifier = 0.7,
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item="Base.SheetMetal",       uses=3,  skills={ Mechanics=4 } },
        { item="Base.SmallSheetMetal",  uses=6,  skills={ Mechanics=4 } },
        { item="Base.CopperSheet",      uses=3,  skills={ Mechanics=4 } },
        { item="Base.SmallCopperSheet", uses=6,  skills={ Mechanics=4 } },
        { item="Base.GoldSheet",        uses=2,  skills={ Mechanics=4 } },
        { item="Base.SilverSheet",      uses=2,  skills={ Mechanics=4 } },
        { item="Base.SmallArmorPlate",  uses=4,  skills={ Mechanics=4 } },
        { item="Base.MetalPipe",        uses=2,  skills={ Mechanics=4 } },
        { item="Base.MetalBar",         uses=2,  skills={ Mechanics=4 } },
        { item="Base.LeadPipe",         uses=4,  skills={ Mechanics=4 } },
        { item="Base.Plank",            uses=6,  skills={ Woodwork=4, Mechanics=4 } },
        { item="Base.AluminumScrap",    uses=12, skills={ Mechanics=4 } },
        { item="Base.BrassScrap",       uses=12, skills={ Mechanics=4 } },
        { item="Base.CopperScrap",      uses=12, skills={ Mechanics=4 } },
        { item="Base.IronScrap",        uses=12, skills={ Mechanics=4 } },
        { item="Base.ScrapMetal",       uses=12, skills={ Mechanics=4 } },
        { item="Base.SteelScrap",       uses=12, skills={ Mechanics=4 } },
        { item="Base.UnusableMetal",    uses=12, skills={ Mechanics=4 } },
      },
    },
  }
}
