----------------------------------------------------------------
-- Recipe Key
--
-- You can put defaults on the recipe itself:
--   require = { 
--      Base.Item1,Base.Item2 }   -- or { "@All_Hoods", Base.Item1 }
--
--   equip = {
--     primary="Base.BlowTorch",  -- or primaryTag="BlowTorch"
--     secondary="Base.Hammer",   -- or secondaryTag="Hammer"
--     wearTag="WeldingMask"      -- or wear="Base.WelderMask"
--     showModel=true,            -- controls hand model visibility during action
--   }
--   anim  = "Welding"
--   sound = "BlowTorch"          -- loops during repair (if set)
--   successSound = "SomeEvent"   -- plays after a successful repair (optional)
--   time  = function(player, brokenItem) return 160 end  -- or a number
--
-- globalItem supports:
--   { item="<FullType>", uses=3, consume=true }
--   { tag ="<TagName>",  uses=3, consume=true }
-- If consume=false, the item is required but NOT consumed.
--
-- Per-fixer overrides:
--   fixer.equip       -- overrides recipe equip for that fixer
--   fixer.globalItem  -- overrides recipe-level globalItem for that fixer
----------------------------------------------------------------

return {
  recipes = {
    {
      name = "Fix Gas Tank Welding",
      require = "@GasTank_All",
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 0.8,
      -- Recipe-level defaults (fixers can override)
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 220,
      fixers = {
        { item = "Base.SheetMetal",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",   uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperSheet",       uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallCopperSheet",  uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.GoldSheet",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SilverSheet",       uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",   uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.AluminumScrap",     uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.BrassScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.IronScrap",         uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.ScrapMetal",        uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SteelScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.UnusableMetal",     uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
      },
    },
    {
      name = "Fix Gas Tank",
      require = "@GasTank_All",
      globalItem = nil,
      conditionModifier = 0.3,
      anim = "VehicleWorkOnMid",
      time  = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.Glue",           uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.DuctTape",       uses = 4, skills = { Mechanics = 3 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 3 }, successSound = "FixWithTape" },
        { item = "Base.Zipties",        uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.Gum",            uses = 4, skills = { Mechanics = 3 } },
      },
    },
    {
      name = "Fix Gas Tank Small Welding",
      require = "@GasTankSmall_All",
      globalItem = { item = "Base.BlowTorch", uses = 2, consume = true },
      conditionModifier = 0.6,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 220,
      fixers = {
        { item = "Base.SheetMetal",        uses = 1, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.SmallSheetMetal",   uses = 2, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.CopperSheet",       uses = 1, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.SmallCopperSheet",  uses = 2, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.GoldSheet",         uses = 1, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.SilverSheet",       uses = 1, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.SmallArmorPlate",   uses = 2, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.AluminumScrap",     uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.BrassScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.CopperScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.IronScrap",         uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.ScrapMetal",        uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.SteelScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
        { item = "Base.UnusableMetal",     uses = 8, skills = { MetalWelding = 3, Mechanics = 2 } },
      },
    },
    {
      name = "Fix Gas Tank Small",
      require = "@GasTankSmall_All",
      globalItem = nil,
      conditionModifier = 0.3,
      anim = "VehicleWorkOnMid",
      time  = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.Glue",           uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.DuctTape",       uses = 2, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.Gum",            uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.Zipties",        uses = 2, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Trailer Welding",
      require = "@Trailer_All",
      globalItem = { item = "Base.BlowTorch", uses = 5, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 4, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 4, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 3, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.AluminumScrap",    uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
      },
    },
    {
      name = "Fix Trailer",
      require = "@Trailer_All",
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.7,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 3, skills = { Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.Plank",            uses = 4, skills = { Woodwork = 3, Mechanics = 3 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true }, },
        { item = "Base.AluminumScrap",    uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { Mechanics = 3 } },
      },
    },
    {
      name = "Fix Trailer 1",
      require = "@Trailer_All",
      globalItem = nil,
      conditionModifier = 0.3,
      anim  = "VehicleWorkOnMid",
      time  = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.Glue",           uses = 4, skills = { Mechanics = 2 } },
        { item = "Base.DuctTape",       uses = 4, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.Zipties",        uses = 4, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Trailer Lids Welding",
      require = "@TrailerLids_All",
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 1.0,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.AluminumScrap",    uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
      },
    },
    {
      name = "Fix Trailer Lids",
      require = "@TrailerLids_All",
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.7,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.Plank",            uses = 2, skills = { Woodwork = 3, Mechanics = 3 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true }, },
        { item = "Base.AluminumScrap",    uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { Mechanics = 3 } },
      },
    },
    {
      name = "Fix Trailer Lids 1",
      require = "@TrailerLids_All",
      globalItem = nil,
      conditionModifier = 0.3,
      anim  = "VehicleWorkOnMid",
      time  = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.Glue",           uses = 4, skills = { Mechanics = 2 } },
        { item = "Base.DuctTape",       uses = 4, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.Zipties",        uses = 4, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Hood Welding",
      require = "@Hood_All",
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 1.0,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 4, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 4, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 3, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.AluminumScrap",    uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { MetalWelding = 3, Mechanics = 3 } },
      },
    },
    {
      name = "Fix Hood",
      require = "@Hood_All",
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.5,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 3, skills = { Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.Plank",            uses = 4, skills = { Woodwork = 3, Mechanics = 3 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true }, },
        { item = "Base.AluminumScrap",    uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { Mechanics = 3 } },
      },
    },
    {
      name = "Fix Military Hood Welding",
      require = "@MilitaryHood_All",
      globalItem = { item = "Base.BlowTorch", uses = 4, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time  = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 3,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.SmallSheetMetal",  uses = 6,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.CopperSheet",      uses = 3,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.SmallCopperSheet", uses = 6,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.GoldSheet",        uses = 2,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.SilverSheet",      uses = 2,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.SmallArmorPlate",  uses = 4,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.MetalPipe",        uses = 2,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.MetalBar",         uses = 2,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.LeadPipe",         uses = 4,  skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.AluminumScrap",    uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.BrassScrap",       uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.CopperScrap",      uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.IronScrap",        uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.ScrapMetal",       uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.SteelScrap",       uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
        { item = "Base.UnusableMetal",    uses = 12, skills = { MetalWelding = 4, Mechanics = 4 } },
      },
    },
    {
      name = "Fix Military Hood",
      require = "@MilitaryHood_All",
      globalItem = { item = "Base.Screws", uses = 16, consume = true },
      conditionModifier = 0.7,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim  = "VehicleWorkOnMid",
      time  = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 3,  skills = { Mechanics = 4 } },
        { item = "Base.SmallSheetMetal",  uses = 6,  skills = { Mechanics = 4 } },
        { item = "Base.CopperSheet",      uses = 3,  skills = { Mechanics = 4 } },
        { item = "Base.SmallCopperSheet", uses = 6,  skills = { Mechanics = 4 } },
        { item = "Base.GoldSheet",        uses = 2,  skills = { Mechanics = 4 } },
        { item = "Base.SilverSheet",      uses = 2,  skills = { Mechanics = 4 } },
        { item = "Base.SmallArmorPlate",  uses = 4,  skills = { Mechanics = 4 } },
        { item = "Base.MetalPipe",        uses = 2,  skills = { Mechanics = 4 } },
        { item = "Base.MetalBar",         uses = 2,  skills = { Mechanics = 4 } },
        { item = "Base.LeadPipe",         uses = 4,  skills = { Mechanics = 4 } },
        { item = "Base.Plank",            uses = 6,  skills = { Woodwork = 4, Mechanics = 4 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true }, },
        { item = "Base.AluminumScrap",    uses = 12, skills = { Mechanics = 4 } },
        { item = "Base.BrassScrap",       uses = 12, skills = { Mechanics = 4 } },
        { item = "Base.CopperScrap",      uses = 12, skills = { Mechanics = 4 } },
        { item = "Base.IronScrap",        uses = 12, skills = { Mechanics = 4 } },
        { item = "Base.ScrapMetal",       uses = 12, skills = { Mechanics = 4 } },
        { item = "Base.SteelScrap",       uses = 12, skills = { Mechanics = 4 } },
        { item = "Base.UnusableMetal",    uses = 12, skills = { Mechanics = 4 } },
      },
    },
    {
      name = "Fix KI5 Wood Parts",
      require = "@WoodParts_All",
      globalItem = { item = "Base.Plank", uses = 3, consume = true },
      conditionModifier = 0.7,
      anim  = "VehicleWorkOnMid",
      time = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 4 } },
        { item = "Base.Glue",           uses = 4, skills = { Mechanics = 4 } },
        { item = "Base.Woodglue",       uses = 2, skills = { Mechanics = 4 } },
        { item = "Base.DuctTape",       uses = 4, skills = { Mechanics = 4 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 4 }, successSound = "FixWithTape" },
        { item = "Base.Zipties",        uses = 4, skills = { Mechanics = 4 } },
      },
    },
    {
      name = "Fix Small Trunk Welding",
      require = "@SmallTrunk_All",
      globalItem = { item = "Base.BlowTorch", uses = 2, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SmallSheetMetal",  uses = 2, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.CopperSheet",      uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SmallCopperSheet", uses = 2, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SmallArmorPlate",  uses = 2, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.MetalBar",         uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.AluminumScrap",    uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.BrassScrap",       uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.CopperScrap",      uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.IronScrap",        uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.ScrapMetal",       uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SteelScrap",       uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.UnusableMetal",    uses = 6, skills = { MetalWelding = 2, Mechanics = 2 } },
      },
    },
    {
      name = "Fix Small Trunk",
      require = "@SmallTrunk_All",
      globalItem = { item = "Base.Screws", uses = 8, consume = true },
      conditionModifier = 0.7,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim = "VehicleWorkOnMid",
      time = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.SmallSheetMetal",  uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.CopperSheet",      uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.SmallCopperSheet", uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.SmallArmorPlate",  uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.MetalBar",         uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.Plank",            uses = 2, skills = { Woodwork = 2, Mechanics = 2 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true } },
        { item = "Base.AluminumScrap",    uses = 6, skills = { Mechanics = 2 } },
        { item = "Base.BrassScrap",       uses = 6, skills = { Mechanics = 2 } },
        { item = "Base.CopperScrap",      uses = 6, skills = { Mechanics = 2 } },
        { item = "Base.IronScrap",        uses = 6, skills = { Mechanics = 2 } },
        { item = "Base.ScrapMetal",       uses = 6, skills = { Mechanics = 2 } },
        { item = "Base.SteelScrap",       uses = 6, skills = { Mechanics = 2 } },
        { item = "Base.UnusableMetal",    uses = 6, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Small Trunk 1",
      require = "@SmallTrunk_All",
      globalItem = nil,
      conditionModifier = 0.3,
      anim = "VehicleWorkOnMid",
      time = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.Glue",           uses = 4, skills = { Mechanics = 2 } },
        { item = "Base.DuctTape",       uses = 4, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.Zipties",        uses = 4, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Trunk Welding",
      require = "@Trunk_All",
      globalItem = { item = "Base.BlowTorch", uses = 3, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 2, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SmallSheetMetal",  uses = 4, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.CopperSheet",      uses = 2, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SmallCopperSheet", uses = 4, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SmallArmorPlate",  uses = 3, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.MetalBar",         uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.AluminumScrap",    uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.IronScrap",        uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { MetalWelding = 2, Mechanics = 2 } },
      },
    },
    {
      name = "Fix Trunk",
      require = "@Trunk_All",
      globalItem = { item = "Base.Screws", uses = 10, consume = true },
      conditionModifier = 0.7,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim = "VehicleWorkOnMid",
      time = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.SmallSheetMetal",  uses = 4, skills = { Mechanics = 2 } },
        { item = "Base.CopperSheet",      uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.SmallCopperSheet", uses = 4, skills = { Mechanics = 2 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.SmallArmorPlate",  uses = 3, skills = { Mechanics = 2 } },
        { item = "Base.MetalPipe",        uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.MetalBar",         uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.LeadPipe",         uses = 1, skills = { Mechanics = 2 } },
        { item = "Base.Plank",            uses = 4, skills = { Woodwork = 2, Mechanics = 2 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true } },
        { item = "Base.AluminumScrap",    uses = 8, skills = { Mechanics = 2 } },
        { item = "Base.BrassScrap",       uses = 8, skills = { Mechanics = 2 } },
        { item = "Base.CopperScrap",      uses = 8, skills = { Mechanics = 2 } },
        { item = "Base.IronScrap",        uses = 8, skills = { Mechanics = 2 } },
        { item = "Base.ScrapMetal",       uses = 8, skills = { Mechanics = 2 } },
        { item = "Base.SteelScrap",       uses = 8, skills = { Mechanics = 2 } },
        { item = "Base.UnusableMetal",    uses = 8, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Trunk 1",
      require = "@Trunk_All",
      globalItem = nil,
      conditionModifier = 0.3,
      anim = "VehicleWorkOnMid",
      time = 120,
      fixers = {
        { item = "Base.Epoxy",          uses = 2, skills = { Mechanics = 2 } },
        { item = "Base.Glue",           uses = 4, skills = { Mechanics = 2 } },
        { item = "Base.DuctTape",       uses = 4, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.FiberglassTape", uses = 2, skills = { Mechanics = 2 }, successSound = "FixWithTape" },
        { item = "Base.Zipties",        uses = 4, skills = { Mechanics = 2 } },
      },
    },
    {
      name = "Fix Trunk Welding Military",
      require = "@TrunkMilitary_All",
      globalItem = { item = "Base.BlowTorch", uses = 4, consume = true },
      conditionModifier = 1.2,
      equip = { primary = "Base.BlowTorch", showModel = true, wearTag = "WeldingMask" },
      anim  = "Welding",
      sound = "BlowTorch",
      time = 220,
      fixers = {
        { item = "Base.SheetMetal",       uses = 3, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 6, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 3, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 6, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 4, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 2, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 3, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.AluminumScrap",    uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 10, skills = { MetalWelding = 3, Mechanics = 3 } },
      },
    },
    {
      name = "Fix Trunk Military",
      require = "@TrunkMilitary_All",
      globalItem = { item = "Base.Screws", uses = 16, consume = true },
      conditionModifier = 0.7,
      equip = { primaryTag = "Screwdriver", showModel = false },
      anim = "VehicleWorkOnMid",
      time = 160,
      fixers = {
        { item = "Base.SheetMetal",       uses = 3, skills = { Mechanics = 3 } },
        { item = "Base.SmallSheetMetal",  uses = 6, skills = { Mechanics = 3 } },
        { item = "Base.CopperSheet",      uses = 3, skills = { Mechanics = 3 } },
        { item = "Base.SmallCopperSheet", uses = 6, skills = { Mechanics = 3 } },
        { item = "Base.GoldSheet",        uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SilverSheet",      uses = 1, skills = { Mechanics = 3 } },
        { item = "Base.SmallArmorPlate",  uses = 4, skills = { Mechanics = 3 } },
        { item = "Base.MetalPipe",        uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.MetalBar",         uses = 2, skills = { Mechanics = 3 } },
        { item = "Base.LeadPipe",         uses = 3, skills = { Mechanics = 3 } },
        { item = "Base.Plank",            uses = 6, skills = { Woodwork = 3, Mechanics = 3 }, equip = { primaryTag = "Hammer", showModel = true }, anim = "Build", globalItem = { item = "Base.Nails", uses = 5, consume = true } },
        { item = "Base.AluminumScrap",    uses = 10, skills = { Mechanics = 3 } },
        { item = "Base.BrassScrap",       uses = 10, skills = { Mechanics = 3 } },
        { item = "Base.CopperScrap",      uses = 10, skills = { Mechanics = 3 } },
        { item = "Base.IronScrap",        uses = 10, skills = { Mechanics = 3 } },
        { item = "Base.ScrapMetal",       uses = 10, skills = { Mechanics = 3 } },
        { item = "Base.SteelScrap",       uses = 10, skills = { Mechanics = 3 } },
        { item = "Base.UnusableMetal",    uses = 10, skills = { Mechanics = 3 } },
      },
    },
  }
}
